error: used `panic!()` or assertion in a function that returns `Result`
  --> tests/ui/panic_in_result_fn_assertions.rs:7:5
   |
LL | /     fn result_with_assert_with_message(x: i32) -> Result<bool, String> // should emit lint
LL | |
LL | |     {
LL | |         assert!(x == 5, "wrong argument");
LL | |         Ok(true)
LL | |     }
   | |_____^
   |
   = help: `panic!()` or assertions should not be used in a function that returns `Result` as `Result` is expected to return an error instead of crashing
note: return Err() instead of panicking
  --> tests/ui/panic_in_result_fn_assertions.rs:10:9
   |
LL |         assert!(x == 5, "wrong argument");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: `-D clippy::panic-in-result-fn` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::panic_in_result_fn)]`

error: used `panic!()` or assertion in a function that returns `Result`
  --> tests/ui/panic_in_result_fn_assertions.rs:14:5
   |
LL | /     fn result_with_assert_eq(x: i32) -> Result<bool, String> // should emit lint
LL | |
LL | |     {
LL | |         assert_eq!(x, 5);
LL | |         Ok(true)
LL | |     }
   | |_____^
   |
   = help: `panic!()` or assertions should not be used in a function that returns `Result` as `Result` is expected to return an error instead of crashing
note: return Err() instead of panicking
  --> tests/ui/panic_in_result_fn_assertions.rs:17:9
   |
LL |         assert_eq!(x, 5);
   |         ^^^^^^^^^^^^^^^^

error: used `panic!()` or assertion in a function that returns `Result`
  --> tests/ui/panic_in_result_fn_assertions.rs:21:5
   |
LL | /     fn result_with_assert_ne(x: i32) -> Result<bool, String> // should emit lint
LL | |
LL | |     {
LL | |         assert_ne!(x, 1);
LL | |         Ok(true)
LL | |     }
   | |_____^
   |
   = help: `panic!()` or assertions should not be used in a function that returns `Result` as `Result` is expected to return an error instead of crashing
note: return Err() instead of panicking
  --> tests/ui/panic_in_result_fn_assertions.rs:24:9
   |
LL |         assert_ne!(x, 1);
   |         ^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

